/**
 * Release a genotype sample's clinician-tier findings, for UI development.
 *
 * ⚠️ THIS IS TEST DATA. IT IS NOT A CLINICAL SIGN-OFF. ⚠️
 *
 * `visibleFindings` withholds every clinician-tier result until an `Interpretation`
 * covering the sample reaches `approved` or `amended`. That gate is correct and stays —
 * but with nothing in the review queue it means the DNA screen renders as fourteen
 * "in review" placeholders, which makes the UI impossible to design against.
 *
 * This writes the approving interpretation so the released state can be built and tested.
 * It is deliberately, visibly synthetic:
 *
 *   - `review.professionalId` is null — no real clinician is implicated
 *   - `review.notes` and `content.summary` both say so in the first sentence
 *   - `model` is 'seed:releaseGenotypeReview' rather than a real model id
 *   - it refuses to run when NODE_ENV is 'production'
 *
 * Those markers are the point. A synthetic approval that reads like a real one is worse
 * than no approval at all, because the whole review pipeline exists to record who actually
 * signed what.
 *
 *   node scripts/releaseGenotypeReview.js <userId>
 *   node scripts/releaseGenotypeReview.js <userId> --revoke
 */
require('dotenv').config();
const mongoose = require('mongoose');
const connectDB = require('../config/db');
const GenotypeFile = require('../models/GenotypeFile');
const Interpretation = require('../models/Interpretation');

const SEED_MODEL = 'seed:releaseGenotypeReview';
const TEST_MARKER =
    'TEST DATA — this interpretation was generated by a seed script, not reviewed by a clinician.';

/** Build interpretation content from what the panel actually found. */
const buildContent = (file) => {
    const called = file.findings.filter((f) => f.status === 'called' && f.tier !== 'suppressed');
    const carriers = called.filter((f) => f.tone === 'carrier' || f.tone === 'attention');
    const rangeAffecting = called.filter((f) => f.affectsBiomarker);
    const incomplete = called.filter((f) => f.incomplete);

    return {
        summary:
            `${TEST_MARKER} ` +
            `A ${file.chip || 'genotyping'} array reported ${file.qc?.totalCalls?.toLocaleString() || 'many'} positions ` +
            `at a ${((file.qc?.callRate ?? 0) * 100).toFixed(1)}% call rate. ` +
            `${called.length} panel variants were called. ` +
            (carriers.length
                ? `${carriers.length} warrant discussion with a clinician. `
                : 'No carrier or attention-level variants were found on this panel. ') +
            `${rangeAffecting.length} adjust the expected range of a biomarker already tracked in LabTrack. ` +
            'An array reports only the positions its chip carries; nothing here rules a condition out.',

        risks: called
            .filter((f) => f.category === 'risk' || f.tone === 'carrier' || f.tone === 'attention')
            .map((f) => ({
                condition: f.name,
                level: f.tone === 'attention' ? 'moderate' : f.tone === 'carrier' ? 'low' : 'low',
                basis: `${f.gene} ${f.genotype}${f.alleleName ? ` (${f.alleleName})` : ''} — ${f.rsid}`,
                rationale: f.detail,
            })),

        recommended_screenings: [],
        specialist_consultations: [],

        lifestyle_recommendations: called
            .filter((f) => f.category === 'nutrition' && f.tone !== 'typical')
            .map((f) => ({
                area: f.name,
                recommendation: f.label,
                rationale: f.detail,
            })),

        biomarkers_of_concern: rangeAffecting.map((f) => ({
            name: f.affectsBiomarker,
            observation: `${f.gene} ${f.genotype} — ${f.label}.`,
            action: 'Interpret this biomarker against the gene-adjusted range shown on its trend screen.',
        })),

        follow_up:
            'Re-run the panel extraction whenever the panel version changes; the stored raw file '
            + 'does not need re-collecting.',

        limitations: [
            TEST_MARKER,
            'A genotyping array reports only positions carried on its chip. A variant not reported '
            + 'was not examined, and is not thereby excluded.',
            ...incomplete.map((f) => `${f.gene}: ${f.incomplete}`),
            ...(file.notTested || []).map((g) => `${g.title}: ${g.detail}`),
            `${file.qc?.indelCalls || 0} insertion/deletion calls were discarded as unreliable and were not interpreted.`,
            'Structural variation, copy number and mitochondrial DNA are outside the reach of this assay.',
        ],
    };
};

(async () => {
    if (process.env.NODE_ENV === 'production') {
        console.error('❌ Refusing to write a synthetic clinician approval in production.');
        process.exit(1);
    }

    const [, , userId, ...flags] = process.argv;
    const revoke = flags.includes('--revoke');

    if (!userId || !mongoose.Types.ObjectId.isValid(userId)) {
        console.error('❌ Usage: node scripts/releaseGenotypeReview.js <userId> [--revoke]');
        process.exit(1);
    }

    await connectDB();

    const file = await GenotypeFile.findOne({ userId }).sort({ createdAt: -1 }).lean();
    if (!file) {
        console.error(`❌ No GenotypeFile for user ${userId}. Run scripts/seedGenotype.js first.`);
        await mongoose.disconnect();
        process.exit(1);
    }

    if (revoke) {
        const { deletedCount } = await Interpretation.deleteMany({
            userId, model: SEED_MODEL, 'covers.id': file._id,
        });
        console.log(`\n🔒 Removed ${deletedCount} seeded approval — clinician-tier findings are withheld again.\n`);
        await mongoose.disconnect();
        return;
    }

    const content = buildContent(file);

    // Idempotent: one seeded approval per sample, refreshed rather than stacked.
    const interpretation = await Interpretation.findOneAndUpdate(
        { userId, model: SEED_MODEL, 'covers.id': file._id },
        {
            $set: {
                userId,
                model: SEED_MODEL,
                generatedAt: new Date(),
                covers: [{ kind: 'genotype_file', id: file._id, date: file.reportedAt }],
                content,
                review: {
                    status: 'approved',
                    // Deliberately null. No real professional signed this.
                    professionalId: null,
                    reviewedAt: new Date(),
                    notes: TEST_MARKER
                        + ' Written by scripts/releaseGenotypeReview.js so the released-state UI can be'
                        + ' built and tested. Must be revoked (--revoke) before any real review flow is'
                        + ' exercised, and cannot be written with NODE_ENV=production.',
                    edits: [],
                },
            },
        },
        { upsert: true, new: true, runValidators: true, setDefaultsOnInsert: true },
    );

    const byTier = (t) => file.findings.filter((f) => f.tier === t && f.status === 'called').length;

    console.log(`\n🧬 GenotypeFile ${file._id}`);
    console.log(`   panel ${file.panelVersion} · ${file.findings.length} findings`);
    console.log(`\n✅ Interpretation ${interpretation._id} — review.status = approved`);
    console.log(`   ⚠️  SYNTHETIC. professionalId is null and the summary says so.`);
    console.log(`\n📋 Content built from the findings:`);
    console.log(`   risks                  ${content.risks.length}`);
    console.log(`   lifestyle              ${content.lifestyle_recommendations.length}`);
    console.log(`   biomarkers of concern  ${content.biomarkers_of_concern.length}`);
    console.log(`   limitations            ${content.limitations.length}`);
    console.log(`\n👁  DNA screen now shows:`);
    console.log(`   release   ${byTier('release')} (already visible)`);
    console.log(`   clinician ${byTier('clinician')} → now released`);
    console.log(`   opt_in    ${byTier('opt_in')} (still hidden until the user consents)`);
    console.log(`\n   Undo with: node scripts/releaseGenotypeReview.js ${userId} --revoke\n`);

    await mongoose.disconnect();
})().catch(async (err) => {
    console.error('❌ Failed:', err.message);
    console.error(err.stack);
    try { await mongoose.disconnect(); } catch { /* already closed */ }
    process.exit(1);
});
